version: '3.5'

services:
  mysql:
      image: mysql:8.0.26
      container_name: pokejournal_mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_DATABASE: pokejournal_mysql
        MYSQL_USER: mysql
        MYSQL_PASSWORD: mysql
      ports:
        - "3306:3306"
      volumes:
           - mysql:/data/postgres
      # volumes:
      #   - ./data:/var/lib/mysql
volumes:
  mysql:
